from . import crm_lead
from . import fal_invoice_milestone
from . import visionet_project
from . import res_users
from . import res_partner
from . import calendar_event
from . import product
from . import mail_tracking_value
from . import mail_activity
from . import mail_message
from . import base_automation